# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MdPaste < Formula
  desc "Convert rich text on the clipboard to Markdown"
  homepage "https://github.com/stn1slv/md-paste"
  version "1.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/stn1slv/md-paste/releases/download/v1.1.0/md-paste_Darwin_x86_64.tar.gz"
    sha256 "d9e6310f6c8ccbde34fb9bd9e946ce7814b878ac4d47b1cd3c0a084d0606a427"

    define_method(:install) do
      bin.install "md-paste"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/stn1slv/md-paste/releases/download/v1.1.0/md-paste_Darwin_arm64.tar.gz"
    sha256 "84cca4da4f6167a58c45bd9caeef89ddc6282dc09212d146662727893066efb2"

    define_method(:install) do
      bin.install "md-paste"
    end
  end

  test do
    system "#{bin}/md-paste", "--version"
  end
end
